import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { db } from "@/src/prisma/db";
export const dynamic="force-dynamic";export const runtime="nodejs";
const text=(v:unknown)=>String(v??"").trim().toLowerCase();const amount=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
function dateValue(v:unknown){if(!v)return null;const d=new Date(String(v));return Number.isNaN(d.getTime())?null:d}function inMonth(v:unknown,s:Date,e:Date){const d=dateValue(v);return Boolean(d&&d>=s&&d<e)}
function activeRecurring(row:any,end:Date){if(text(row.status)!=="active")return false;const s=dateValue(row.startDate),e=dateValue(row.endDate);return(!s||s<end)&&(!e||e>=new Date(end.getFullYear(),end.getMonth()-1,1))}
export async function GET(request:Request){const session=await auth();if(!session?.user)return NextResponse.json({success:false,message:"Unauthorized"},{status:401});try{const url=new URL(request.url),monthParam=url.searchParams.get("month"),parsed=monthParam&&/^\d{4}-\d{2}$/.test(monthParam)?new Date(`${monthParam}-01T00:00:00`):new Date(),monthStart=new Date(parsed.getFullYear(),parsed.getMonth(),1),monthEnd=new Date(parsed.getFullYear(),parsed.getMonth()+1,1);
const[samples,companies,locations,recurring,workOrders,payments,reports,quotations]=await Promise.all([db.orm.public.Sample.all(),db.orm.public.Company.all(),db.orm.public.Location.all(),db.orm.public.RecurringService.all(),db.orm.public.WorkOrder.all(),db.orm.public.Payment.all(),db.orm.public.Report.all(),db.orm.public.Quotation.all()]);
const companyMap=new Map(companies.map((r:any)=>[r.id,r.name])),locationMap=new Map(locations.map((r:any)=>[r.id,r.name])),recurringRows=recurring.filter((r:any)=>activeRecurring(r,monthEnd)),recurringTarget=recurringRows.reduce((s:number,r:any)=>s+amount(r.samplesPerMonth),0),monthSamples=samples.filter((r:any)=>inMonth(r.collectionDate,monthStart,monthEnd)),collectedQuantity=monthSamples.reduce((s:number,r:any)=>s+amount(r.sampleCount),0);
const recurringByKey=new Map<string,number>();for(const r of recurringRows as any[]){const k=`${r.companyId}|${r.locationId||""}|${text(r.sampleType)}`;recurringByKey.set(k,(recurringByKey.get(k)||0)+amount(r.samplesPerMonth))}const recurringCollectedByKey=new Map<string,number>();let recurringCollected=0,oneTimeSamples=0;for(const sample of monthSamples as any[]){const k=`${sample.companyId}|${sample.locationId||""}|${text(sample.sampleType)}`,target=recurringByKey.get(k)||0,used=recurringCollectedByKey.get(k)||0,qty=amount(sample.sampleCount),rq=Math.min(qty,Math.max(0,target-used));recurringCollected+=rq;oneTimeSamples+=qty-rq;recurringCollectedByKey.set(k,used+rq)}
const recurringProgress=recurringRows.map((r:any)=>{const k=`${r.companyId}|${r.locationId||""}|${text(r.sampleType)}`,target=amount(r.samplesPerMonth),collected=Math.min(target,recurringCollectedByKey.get(k)||0);return{id:r.id,companyName:companyMap.get(r.companyId)||"Unknown Company",locationName:r.locationId?locationMap.get(r.locationId)||"Unknown Location":"No Location",service:r.service,sampleType:r.sampleType,target,collected,remaining:Math.max(0,target-collected),completionPercent:target?Math.min(100,Math.round(collected/target*100)):0}});
const sampleMix:Record<string,number>={};for(const r of monthSamples as any[]){const k=r.sampleType||"Other";sampleMix[k]=(sampleMix[k]||0)+amount(r.sampleCount)}const monthOrders=workOrders.filter((r:any)=>inMonth(r.confirmedDate,monthStart,monthEnd)),orderValue=monthOrders.reduce((s:number,r:any)=>s+amount(r.totalAmount),0),receivedStatuses=new Set(["received","paid","collected","completed"]),receivedPayments=payments.filter((r:any)=>receivedStatuses.has(text(r.status))),monthPayments=receivedPayments.filter((r:any)=>inMonth(r.paymentDate,monthStart,monthEnd)),paymentsReceived=monthPayments.reduce((s:number,r:any)=>s+amount(r.amount),0);
const paymentByOrder=new Map<string,number>();for(const p of receivedPayments as any[])if(p.workOrderId)paymentByOrder.set(p.workOrderId,(paymentByOrder.get(p.workOrderId)||0)+amount(p.amount));const pendingPayments=(workOrders as any[]).map(o=>({id:o.id,workOrderNumber:o.workOrderNumber,companyName:companyMap.get(o.companyId)||"Unknown Company",totalAmount:amount(o.totalAmount),receivedAmount:paymentByOrder.get(o.id)||0,pendingAmount:Math.max(0,amount(o.totalAmount)-(paymentByOrder.get(o.id)||0))})).filter(r=>r.pendingAmount>.01);
const duplicateNumbers=new Map<string,any[]>();for(const s of samples as any[]){const k=text(s.sampleNumber);if(k)duplicateNumbers.set(k,[...(duplicateNumbers.get(k)||[]),s])}const dataQuality={missingExpectedDate:(samples as any[]).filter(r=>text(r.status)!=="planned"&&!text(r.reportStatus).includes("deliver")&&!r.expectedCompletionDate).length,missingTestingLocation:(samples as any[]).filter(r=>["received at lab","testing","completed"].includes(text(r.status))&&!String(r.testingLocation||"").trim()).length,deliveredWithoutDate:(samples as any[]).filter(r=>text(r.reportStatus).includes("deliver")&&!r.reportDeliveredDate).length,duplicateSampleNumbers:[...duplicateNumbers.values()].filter(r=>r.length>1).length,ordersWithoutQuotation:(workOrders as any[]).filter(r=>!r.quotationId).length,paymentsWithoutReference:(payments as any[]).filter(r=>!r.workOrderId&&!r.quotationId).length,recurringWithoutLocation:(recurringRows as any[]).filter(r=>!r.locationId).length,invalidSampleQuantity:(samples as any[]).filter(r=>amount(r.sampleCount)<=0).length};
const reportReady=(samples as any[]).filter(r=>["ready","approved"].some(s=>text(r.reportStatus).includes(s))&&!text(r.reportStatus).includes("deliver")).length,reportDelivered=(samples as any[]).filter(r=>text(r.reportStatus).includes("deliver")).length,testingPending=(samples as any[]).filter(r=>["received at lab","testing"].includes(text(r.status))).length,reportsPending=(samples as any[]).filter(r=>text(r.status)!=="planned"&&!text(r.reportStatus).includes("deliver")).length;
const samplesByQuotation=new Map<string,any[]>();for(const s of samples as any[])if(s.quotationId)samplesByQuotation.set(s.quotationId,[...(samplesByQuotation.get(s.quotationId)||[]),s]);const orderLifecycle=(workOrders as any[]).map(o=>{const linked=o.quotationId?(samplesByQuotation.get(o.quotationId)||[]):[],received=paymentByOrder.get(o.id)||0,total=amount(o.totalAmount),allDelivered=linked.length>0&&linked.every(s=>text(s.reportStatus).includes("deliver")),anyTesting=linked.some(s=>["received at lab","testing","completed"].includes(text(s.status))),anyCollected=linked.some(s=>text(s.status)!=="planned"),paid=total<=0||received>=total-.01;let stage="Confirmed";if(paid&&allDelivered)stage="Closed";else if(allDelivered)stage="Report Delivered";else if(anyTesting)stage="Testing";else if(anyCollected)stage="Samples Collected";else if(linked.length)stage="Work Started";return{id:o.id,workOrderNumber:o.workOrderNumber,companyName:companyMap.get(o.companyId)||"Unknown Company",service:o.service,stage,totalAmount:total,receivedAmount:received,pendingAmount:Math.max(0,total-received),sampleRecords:linked.length,sampleQuantity:linked.reduce((sum:number,s:any)=>sum+amount(s.sampleCount),0)}}).sort((a,b)=>b.pendingAmount-a.pendingAmount);
const actionRequired={recurringCollectionsRemaining:Math.max(0,recurringTarget-recurringCollected),reportsPending,reportsReady:reportReady,testingPending,paymentsPending:pendingPayments.length,pendingPaymentValue:pendingPayments.reduce((s,r)=>s+r.pendingAmount,0),dataQualityIssues:Object.values(dataQuality).reduce((s,v)=>s+Number(v||0),0)};
return NextResponse.json({success:true,month:`${monthStart.getFullYear()}-${String(monthStart.getMonth()+1).padStart(2,"0")}`,generatedAt:new Date().toISOString(),monthly:{recurringTarget,recurringCollected,recurringRemaining:Math.max(0,recurringTarget-recurringCollected),recurringCompletionPercent:recurringTarget?Math.min(100,Math.round(recurringCollected/recurringTarget*100)):0,oneTimeSamples,totalCollected:collectedQuantity,testingPending,reportsPending,reportsReady:reportReady,reportsDelivered:reportDelivered,ordersReceived:monthOrders.length,orderValue,paymentsReceived,pendingPaymentValue:actionRequired.pendingPaymentValue},sampleMix,recurringProgress,pendingPayments:pendingPayments.sort((a,b)=>b.pendingAmount-a.pendingAmount).slice(0,50),orderLifecycle:orderLifecycle.slice(0,50),actionRequired,dataQuality,counts:{companies:companies.length,quotations:quotations.length,reports:reports.length}})}catch(error){console.error("GET /api/business/summary error:",error);return NextResponse.json({success:false,message:"Unable to load business summary."},{status:500})}}
