import Link from "next/link";
import { ArrowLeft, ArrowRight, CircleDollarSign, Gauge, Target, TrendingUp, UsersRound, WalletCards } from "lucide-react";
import { db } from "@/src/prisma/db";
import "../management.css";
import "./team.css";

export const dynamic = "force-dynamic";
type Row = Record<string, unknown>;
type Stats = { leads:number; active:number; quotes:number; orders:number; business:number; collections:number; overdue:number; monthLeads:number; monthQuotes:number; monthOrders:number; monthBusiness:number; monthCollections:number };
async function rows(t:"Lead"|"Quotation"|"WorkOrder"|"Payment"){try{return await(db.orm.public[t] as unknown as {all:()=>Promise<Row[]>}).all()}catch{return[]}}
const n=(v:unknown)=>Number(v||0),txt=(v:unknown)=>String(v||"").trim(),low=(v:unknown)=>txt(v).toLowerCase(),money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v),pct=(a:number,b:number)=>b?`${Math.round(a/b*100)}%`:"0%";
const active=(s:unknown)=>!["inactive","cancelled","canceled","closed","rejected","void","won","lost"].includes(low(s)),valid=(s:unknown)=>!["cancelled","canceled","rejected","void"].includes(low(s)),paid=(s:unknown)=>["received","paid","collected","completed"].includes(low(s));
function overdue(x:Row){if(!x.nextFollowUp)return false;const d=new Date(String(x.nextFollowUp));if(Number.isNaN(d.getTime()))return false;const z=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()<new Date(z.getFullYear(),z.getMonth(),z.getDate()).getTime()}
function thisMonth(v:unknown){const d=new Date(String(v||"")),z=new Date();return !Number.isNaN(d.getTime())&&d.getFullYear()===z.getFullYear()&&d.getMonth()===z.getMonth()}
const href=(x:string)=>`/admin/management/owner/${encodeURIComponent(x)}`;
export default async function Page(){
 const[l,q,o,p]=await Promise.all([rows("Lead"),rows("Quotation"),rows("WorkOrder"),rows("Payment")]);
 const owners=new Map<string,Stats>();
 const get=(v:unknown)=>{const k=txt(v)||"Unassigned";if(!owners.has(k))owners.set(k,{leads:0,active:0,quotes:0,orders:0,business:0,collections:0,overdue:0,monthLeads:0,monthQuotes:0,monthOrders:0,monthBusiness:0,monthCollections:0});return owners.get(k)!};
 l.forEach(x=>{const a=get(x.salesOwner);a.leads++;if(active(x.status))a.active++;if(active(x.status)&&overdue(x))a.overdue++;if(thisMonth(x.createdAt))a.monthLeads++});
 q.forEach(x=>{const a=get(x.salesOwner);a.quotes++;if(thisMonth(x.quotationDate||x.createdAt))a.monthQuotes++});
 const vo=o.filter(x=>valid(x.status));vo.forEach(x=>{const a=get(x.salesOwner);a.orders++;a.business+=n(x.totalAmount);if(thisMonth(x.confirmedDate||x.createdAt)){a.monthOrders++;a.monthBusiness+=n(x.totalAmount)}});
 p.filter(x=>paid(x.status)).forEach(x=>{const wo=o.find(w=>String(w.id)===String(x.workOrderId)),qt=q.find(z=>String(z.id)===String(x.quotationId)),a=get(wo?.salesOwner||qt?.salesOwner);a.collections+=n(x.amount);if(thisMonth(x.paymentDate||x.createdAt))a.monthCollections+=n(x.amount)});
 const list=[...owners].sort((a,b)=>b[1].monthBusiness-a[1].monthBusiness||b[1].business-a[1].business),business=list.reduce((a,[,x])=>a+x.business,0),collections=list.reduce((a,[,x])=>a+x.collections,0),attention=list.reduce((a,[,x])=>a+x.overdue,0),monthBusiness=list.reduce((a,[,x])=>a+x.monthBusiness,0),monthCollections=list.reduce((a,[,x])=>a+x.monthCollections,0),monthOrders=list.reduce((a,[,x])=>a+x.monthOrders,0),monthQuotes=list.reduce((a,[,x])=>a+x.monthQuotes,0),monthLeads=list.reduce((a,[,x])=>a+x.monthLeads,0);
 const label=new Date().toLocaleString("en-IN",{month:"long",year:"numeric"});
 return <main className="mi-page"><header className="mi-owner-hero tp-hero"><div><Link href="/admin/management" className="mi-back"><ArrowLeft size={15}/> Management</Link><span>V9 • REAL-TIME TEAM INTELLIGENCE</span><h1>Individual Sales Performance</h1><p>Current-month momentum plus complete owner history. Every owner card opens the underlying lead → quotation → order → collection trail.</p></div><div className="mi-owner-health"><UsersRound/><div><small>OWNERS</small><strong>{list.length}</strong><span>tracked individually</span></div></div></header>
 <section className="tp-period"><div><span>LIVE PERIOD</span><strong>{label}</strong></div><div><span>MONTH LEADS</span><strong>{monthLeads}</strong></div><div><span>MONTH QUOTES</span><strong>{monthQuotes}</strong></div><div><span>MONTH ORDERS</span><strong>{monthOrders}</strong></div><div><span>MONTH BUSINESS</span><strong>{money(monthBusiness)}</strong></div><div><span>MONTH COLLECTIONS</span><strong>{money(monthCollections)}</strong></div></section>
 <section className="tp-kpis"><Link href="/admin/leads"><Target/><span>Total Leads</span><strong>{l.length}</strong></Link><Link href="/admin/orders"><TrendingUp/><span>Lifetime Business</span><strong>{money(business)}</strong></Link><Link href="/admin/payments"><CircleDollarSign/><span>Lifetime Collections</span><strong>{money(collections)}</strong></Link><Link href="/admin/follow-ups"><WalletCards/><span>Overdue Follow-ups</span><strong>{attention}</strong></Link></section>
 <section className="mi-panel tp-panel"><div className="mi-panel-head"><div><span>OWNER COMPARISON</span><h2>Current month performance with complete commercial context</h2></div><Gauge/></div><div className="tp-grid">{list.map(([name,a])=><Link href={href(name)} className="tp-owner" key={name}><div className="tp-top"><span className="tp-avatar">{name.charAt(0).toUpperCase()}</span><div><strong>{name}</strong><small>{a.active} active leads · {a.overdue} overdue</small></div><ArrowRight/></div><div className="tp-month"><span><small>This month business</small><b>{money(a.monthBusiness)}</b></span><span><small>This month collected</small><b>{money(a.monthCollections)}</b></span><span><small>Month orders</small><b>{a.monthOrders}</b></span></div><div className="tp-stats"><span><small>Leads</small><b>{a.leads}</b></span><span><small>Quotes</small><b>{a.quotes}</b></span><span><small>Orders</small><b>{a.orders}</b></span><span><small>Lead→Quote</small><b>{pct(a.quotes,a.leads)}</b></span><span><small>Quote→Order</small><b>{pct(a.orders,a.quotes)}</b></span><span><small>Lead→Order</small><b>{pct(a.orders,a.leads)}</b></span><span><small>Collection</small><b>{pct(a.collections,a.business)}</b></span><span><small>Open leads</small><b>{a.active}</b></span></div><div className="tp-money"><span><small>Total Business</small><b>{money(a.business)}</b></span><span><small>Total Collected</small><b>{money(a.collections)}</b></span><span><small>Outstanding</small><b>{money(Math.max(a.business-a.collections,0))}</b></span></div></Link>)}{list.length===0&&<p className="mi-empty">No sales owners are available yet.</p>}</div></section>
 <section className="tp-explain"><Gauge/><div><strong>How management should read this</strong><span>The first row shows live activity for {label}. Owner cards combine current-month momentum with lifetime conversion and collection performance. No target values are invented; target-vs-actual will activate only after persisted management targets are added.</span></div></section></main>
}
