import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { db } from "@/src/prisma/db";
export const runtime="nodejs";
type Body={id?:string;name?:string;company?:string;companyId?:string|null;phone?:string;email?:string;service?:string;requirement?:string;website?:string;source?:string;salesOwner?:string|null;status?:string;notes?:string;nextFollowUp?:string};
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,PHONE=/^[0-9+\-()\s]{7,20}$/;
const norm=(v:string|null|undefined)=>v?v.slice(0,10):null;
async function notify(x:{id:string;name:string;company:string;service:string;status:string;next:string|null;statusChanged:boolean;followChanged:boolean}){try{let type="LEAD_UPDATED",title="Lead updated",message=`${x.name} - ${x.company} - ${x.service}`;if(x.statusChanged&&x.followChanged&&x.next){type="LEAD_STATUS_AND_FOLLOW_UP_CHANGED";title="Lead status & follow-up updated";message=`${x.name} - ${x.company} - ${x.status} - Follow-up ${x.next}`}else if(x.followChanged&&x.next){type="FOLLOW_UP_SCHEDULED";title="Lead follow-up scheduled";message=`${x.name} - ${x.company} - ${x.next}`}else if(x.followChanged&&!x.next){type="FOLLOW_UP_CLEARED";title="Lead follow-up cleared";message=`${x.name} - ${x.company} - ${x.status}`}else if(x.statusChanged){type="LEAD_STATUS_CHANGED";title=`Lead status: ${x.status}`}await db.orm.public.Notification.create({type,title,message,entityType:"Lead",entityId:x.id,actionUrl:`/admin/leads/${x.id}`,isRead:false})}catch(e){console.error("Lead notification error:",e)}}
export async function GET(){const s=await auth();if(!s?.user)return NextResponse.json({success:false,message:"Unauthorized"},{status:401});try{return NextResponse.json(await db.orm.public.Lead.orderBy(l=>l.createdAt.desc()).all())}catch{return NextResponse.json({success:false,message:"Unable to load leads."},{status:500})}}
export async function POST(request:Request){try{const len=request.headers.get("content-length");if(len&&Number(len)>10000)return NextResponse.json({success:false,message:"Submission is too large."},{status:413});const b:Body=await request.json();if(b.website?.trim())return NextResponse.json({success:true,message:"Enquiry submitted successfully."});const s=await auth(),isAdmin=Boolean(s?.user),source=isAdmin&&b.source?.trim()?b.source.trim():"Nexus Hyderabad Website";const name=b.name?.trim()||"",company=b.company?.trim()||"",phone=b.phone?.trim()||"",email=b.email?.trim().toLowerCase()||"",service=b.service?.trim()||"",requirement=b.requirement?.trim()||"";if(!name||!company||!phone||!service||!requirement)return NextResponse.json({success:false,message:"Please complete all required fields."},{status:400});if(!PHONE.test(phone)||(email&&!EMAIL.test(email)))return NextResponse.json({success:false,message:"Please enter valid contact details."},{status:400});const lead=await db.orm.public.Lead.create({name,company,companyId:null,phone,email,service,requirement,source,salesOwner:isAdmin?(b.salesOwner?.trim()||null):null,status:isAdmin?(b.status?.trim()||"New Lead"):"New Lead",isRead:isAdmin,notes:isAdmin?(b.notes?.trim()||null):null,nextFollowUp:isAdmin?(b.nextFollowUp?.trim()||null):null});if(isAdmin&&source==="Inbound Call")try{await db.orm.public.Notification.create({type:"INBOUND_CALL",title:"Inbound customer call logged",message:`${name} - ${company} - ${service}`,entityType:"Lead",entityId:lead.id,actionUrl:`/admin/leads/${lead.id}`,isRead:false})}catch{}return NextResponse.json({success:true,message:"Lead saved successfully.",lead},{status:201})}catch(e){console.error(e);return NextResponse.json({success:false,message:"Unable to save lead."},{status:500})}}
export async function PUT(request:Request){const s=await auth();if(!s?.user)return NextResponse.json({success:false,message:"Unauthorized"},{status:401});try{const b:Body=await request.json(),id=b.id?.trim();if(!id)return NextResponse.json({success:false,message:"Lead ID is required."},{status:400});const old=await db.orm.public.Lead.where({id}).first();if(!old)return NextResponse.json({success:false,message:"Lead not found."},{status:404});const status=b.status?.trim()||old.status,notes=b.notes!==undefined?b.notes.trim()||null:old.notes,salesOwner=b.salesOwner!==undefined?(b.salesOwner?.trim()||null):old.salesOwner;let next=b.nextFollowUp!==undefined?b.nextFollowUp.trim()||null:old.nextFollowUp,companyId=old.companyId;if(b.companyId!==undefined){const requested=b.companyId?.trim()||null;if(requested&&!await db.orm.public.Company.where({id:requested}).first())return NextResponse.json({success:false,message:"Selected company was not found."},{status:404});companyId=requested}if(status==="Won"||status==="Lost")next=null;const statusChanged=old.status!==status,followChanged=norm(old.nextFollowUp)!==norm(next);const updated=await db.orm.public.Lead.where({id}).update({status,notes,nextFollowUp:next,companyId,salesOwner});if(statusChanged||followChanged){let company=old.company;if(companyId){const c=await db.orm.public.Company.where({id:companyId}).first();if(c?.name)company=c.name}await notify({id,name:old.name,company,service:old.service,status,next,statusChanged,followChanged})}return NextResponse.json({success:true,message:"Lead updated successfully.",lead:updated})}catch(e){console.error(e);return NextResponse.json({success:false,message:"Unable to update lead."},{status:500})}}
