"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { Activity, ArrowRight, ArrowUpRight, BarChart3, Building2, CalendarDays, CircleDollarSign, ClipboardList, FileText, FlaskConical, FolderOpen, LayoutDashboard, Loader2, Megaphone, RefreshCw, Search, Settings2, UploadCloud, UserRound, Users, WalletCards, X } from "lucide-react";
import AdminLogoutButton from "@/components/AdminLogoutButton";

type SearchResult={id:string;type:"company"|"contact"|"lead"|"quotation"|"sample"|"report";title:string;subtitle:string;detail:string;href:string;companyId:string|null};
const navigation=[
{label:"Dashboard",href:"/admin",icon:LayoutDashboard},{label:"Operations",href:"/admin/operations",icon:Activity},{label:"Business MIS",href:"/admin/business",icon:BarChart3},{label:"Clients",href:"/admin/companies",icon:Building2},{label:"Lead Management",href:"/admin/leads",icon:Users},{label:"Quotations",href:"/admin/quotations",icon:CircleDollarSign},{label:"Orders",href:"/admin/orders",icon:ClipboardList},{label:"Recurring Services",href:"/admin/recurring-services",icon:RefreshCw},{label:"Sample Collection",href:"/admin/samples",icon:FlaskConical},{label:"Identification Import",href:"/admin/identification-import",icon:UploadCloud},{label:"Reports",href:"/admin/reports",icon:FileText},{label:"Payments",href:"/admin/payments",icon:WalletCards},{label:"Follow-ups",href:"/admin/follow-ups",icon:CalendarDays},{label:"Monthly Plan",href:"/admin/monthly-plan",icon:CalendarDays},{label:"Digital Marketing",href:"/admin/digital-marketing",icon:Megaphone},{label:"Documents",href:"/admin/documents",icon:FolderOpen},{label:"Settings",href:"/admin/settings",icon:Settings2}];
function SearchResultIcon({type}:{type:SearchResult["type"]}){switch(type){case"company":return <Building2 size={16}/>;case"contact":return <UserRound size={16}/>;case"lead":return <Users size={16}/>;case"quotation":return <CircleDollarSign size={16}/>;case"sample":return <FlaskConical size={16}/>;case"report":return <FileText size={16}/>;default:return <Search size={16}/>}}
function resultTypeLabel(type:SearchResult["type"]){return type.charAt(0).toUpperCase()+type.slice(1)}
export default function AdminSidebar(){const pathname=usePathname();const[newLeadCount,setNewLeadCount]=useState(0);const[searchQuery,setSearchQuery]=useState("");const[searchResults,setSearchResults]=useState<SearchResult[]>([]);const[searchLoading,setSearchLoading]=useState(false);const[searchOpen,setSearchOpen]=useState(false);const[searchError,setSearchError]=useState("");const searchRequestRef=useRef<AbortController|null>(null);
useEffect(()=>{async function loadNotifications(){try{const response=await fetch("/api/notifications",{cache:"no-store"});if(!response.ok)return;const data=await response.json();setNewLeadCount(data.newLeads??0)}catch(error){console.error("Sidebar notification error:",error)}}void loadNotifications();const interval=setInterval(loadNotifications,30000);return()=>clearInterval(interval)},[pathname]);
useEffect(()=>{const query=searchQuery.trim();if(query.length<2){searchRequestRef.current?.abort();setSearchResults([]);setSearchLoading(false);setSearchError("");return}const timer=setTimeout(async()=>{searchRequestRef.current?.abort();const controller=new AbortController();searchRequestRef.current=controller;setSearchLoading(true);setSearchError("");try{const response=await fetch(`/api/search?q=${encodeURIComponent(query)}`,{cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("Search request failed");const data=await response.json();setSearchResults(data.results??[]);setSearchOpen(true)}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;console.error("CRM search error:",error);setSearchResults([]);setSearchError("Unable to search CRM.");setSearchOpen(true)}finally{if(searchRequestRef.current===controller)setSearchLoading(false)}},300);return()=>clearTimeout(timer)},[searchQuery]);
useEffect(()=>{setSearchOpen(false);setSearchQuery("");setSearchResults([]);setSearchError("")},[pathname]);function clearSearch(){searchRequestRef.current?.abort();setSearchQuery("");setSearchResults([]);setSearchError("");setSearchOpen(false);setSearchLoading(false)}function isActive(href:string){return href==="/admin"?pathname==="/admin":pathname.startsWith(href)}
return <aside className="admin-shell-sidebar nexus-dashboard-sidebar"><Link href="/admin" className="admin-shell-brand"><div className="admin-shell-logo"><img src="/nexus-logo.png" alt="Nexus Test Labs"/></div><div className="admin-shell-brand-text"><strong>Nexus Test Labs</strong><span>Hyderabad Operations</span></div></Link>
<div className="admin-crm-search"><div className="admin-crm-search-box"><Search size={16} className="admin-crm-search-icon"/><input type="text" value={searchQuery} placeholder="Search CRM..." autoComplete="off" aria-label="Search CRM" onFocus={()=>{if(searchQuery.trim().length>=2)setSearchOpen(true)}} onChange={event=>setSearchQuery(event.target.value)}/>{searchLoading&&<Loader2 size={15} className="admin-crm-search-loader"/>}{!searchLoading&&searchQuery&&<button type="button" className="admin-crm-search-clear" onClick={clearSearch} aria-label="Clear search"><X size={14}/></button>}</div>
{searchOpen&&searchQuery.trim().length>=2&&<div className="admin-crm-search-results"><div className="admin-crm-search-results-header"><span>Search Results</span>{!searchLoading&&<strong>{searchResults.length}</strong>}</div>{searchLoading&&searchResults.length===0&&<div className="admin-crm-search-state"><Loader2 size={18} className="admin-crm-search-state-loader"/><span>Searching CRM...</span></div>}{!searchLoading&&searchError&&<div className="admin-crm-search-state error">{searchError}</div>}{!searchLoading&&!searchError&&searchResults.length===0&&<div className="admin-crm-search-state">No CRM records found.</div>}{searchResults.map(result=><Link key={`${result.type}-${result.id}`} href={result.href} className="admin-crm-search-result" onClick={()=>setSearchOpen(false)}><span className={`admin-crm-search-result-icon ${result.type}`}><SearchResultIcon type={result.type}/></span><span className="admin-crm-search-result-copy"><span><strong>{result.title}</strong><small>{resultTypeLabel(result.type)}</small></span><em>{result.subtitle}</em>{result.detail&&<small>{result.detail}</small>}</span><ArrowUpRight size={14}/></Link>)}</div>}</div>
<nav className="admin-shell-nav">{navigation.map(item=>{const Icon=item.icon;const active=isActive(item.href);return <Link key={item.href} href={item.href} className={`admin-shell-nav-link ${active?"active":""}`}><Icon size={17}/><span>{item.label}</span>{item.href==="/admin/leads"&&newLeadCount>0&&<span className="admin-shell-nav-badge">{newLeadCount}</span>}{active&&<ArrowRight size={14} className="admin-shell-nav-arrow"/>}</Link>})}</nav>
<div className="admin-shell-footer"><div className="admin-shell-status"><span/><div><strong>Operations Online</strong><small>Hyderabad CRM</small></div></div><AdminLogoutButton/></div></aside>}
