"use client";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Building2,CalendarDays,CheckCircle2,Loader2,Save,UserRound } from "lucide-react";
type Lead={id:string;status:string;notes?:string;nextFollowUp?:string;companyId?:string|null;salesOwner?:string|null};type Company={id:string;name:string;status:string};
const statuses=["New Lead","Contacted","Visited","Meeting Scheduled","Requirement Identified","Quotation Sent","Follow-up","Won","Lost"];
function dateValue(v?:string){return v?v.slice(0,10):""}
export default function LeadEditor({lead}:{lead:Lead}){const router=useRouter();const[status,setStatus]=useState(lead.status),[notes,setNotes]=useState(lead.notes||""),[nextFollowUp,setNextFollowUp]=useState(dateValue(lead.nextFollowUp)),[companyId,setCompanyId]=useState(lead.companyId||""),[salesOwner,setSalesOwner]=useState(lead.salesOwner||""),[companies,setCompanies]=useState<Company[]>([]),[companiesLoading,setCompaniesLoading]=useState(true),[loading,setLoading]=useState(false),[success,setSuccess]=useState(false),[error,setError]=useState("");
useEffect(()=>{(async()=>{try{const r=await fetch("/api/companies",{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();setCompanies(Array.isArray(d)?d:[])}catch{setError("Unable to load company list.")}finally{setCompaniesLoading(false)}})()},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setSuccess(false);setError("");try{const r=await fetch("/api/leads",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:lead.id,status,notes,nextFollowUp,companyId:companyId||null,salesOwner:salesOwner.trim()||null})});const result=await r.json();if(!r.ok)throw new Error(result.message||"Unable to update lead.");if(status==="Won"||status==="Lost")setNextFollowUp("");setSuccess(true);router.refresh();setTimeout(()=>setSuccess(false),3000)}catch(e){setError(e instanceof Error?e.message:"Something went wrong.")}finally{setLoading(false)}}
return <form className="lead-editor" onSubmit={submit}><div className="lead-editor-header"><div><span>Lead Management</span><h2>Update Lead</h2></div><Save size={20}/></div><div className="lead-editor-field"><label htmlFor="salesOwner"><UserRound size={15}/>Sales Owner</label><input id="salesOwner" value={salesOwner} onChange={e=>setSalesOwner(e.target.value)} placeholder="Example: Venkat"/><small>Used for individual sales contribution and management reporting.</small></div><div className="lead-editor-field"><label htmlFor="companyId"><Building2 size={15}/>Linked Company</label><select id="companyId" value={companyId} onChange={e=>setCompanyId(e.target.value)} disabled={companiesLoading}><option value="">{companiesLoading?"Loading companies...":"Not linked to a company"}</option>{companies.map(c=><option value={c.id} key={c.id}>{c.name}{c.status?` — ${c.status}`:""}</option>)}</select></div><div className="lead-editor-field"><label htmlFor="leadStatus">Lead Status</label><select id="leadStatus" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option value={s} key={s}>{s}</option>)}</select></div><div className="lead-editor-field"><label htmlFor="nextFollowUp"><CalendarDays size={15}/>Next Follow-up</label><input id="nextFollowUp" type="date" value={nextFollowUp} disabled={status==="Won"||status==="Lost"} onChange={e=>setNextFollowUp(e.target.value)}/></div><div className="lead-editor-field"><label htmlFor="leadNotes">Notes</label><textarea id="leadNotes" value={notes} onChange={e=>setNotes(e.target.value)} rows={7} placeholder="Client discussion, requirement and next action..."/></div><button type="submit" className="lead-save-button" disabled={loading}>{loading?<><Loader2 size={17} className="submit-spinner"/>Saving...</>:<><Save size={17}/>Save Lead</>}</button>{success&&<div className="lead-update-success"><CheckCircle2 size={18}/>Lead updated successfully.</div>}{error&&<div className="form-error">{error}</div>}</form>}
