import Link from "next/link";
import{notFound}from"next/navigation";
import{db}from"@/src/prisma/db";
import{ArrowLeft,ArrowRight,Building2,CalendarDays,CheckCircle2,CircleDollarSign,ClipboardList,FileText,FlaskConical,Mail,MapPin,Phone,ReceiptText,User,UserRound,WalletCards}from"lucide-react";
import LeadEditor from"@/components/LeadEditor";
import"./journey.css";
export const dynamic="force-dynamic";
type Lead={id:string;name:string;company:string;companyId:string|null;phone:string;email:string;service:string;requirement:string;source:string;salesOwner:string|null;status:string;isRead:boolean;notes:string|null;nextFollowUp:string|null;createdAt:string;updatedAt:string};type Row=Record<string,unknown>;
const fmt=(v:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));const follow=(v:string|null)=>v?new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v)):"Not scheduled";const text=(v:unknown)=>String(v??"").trim();const money=(v:unknown)=>`₹${Number(v||0).toLocaleString("en-IN")}`;async function related(model:{where:(x:{companyId:string})=>{all:()=>unknown}},companyId:string):Promise<Row[]>{try{return await model.where({companyId}).all() as unknown as Row[]}catch{return[]}}
export default async function Page({params}:{params:Promise<{id:string}>}){const{id}=await params;let lead:Lead|null=null;try{lead=await db.orm.public.Lead.where({id}).first() as Lead|null}catch{}if(!lead)notFound();if(!lead.isRead)try{await db.orm.public.Lead.where({id}).update({isRead:true})}catch{}
 let activities:Row[]=[],quotes:Row[]=[],orders:Row[]=[],samples:Row[]=[],reports:Row[]=[],payments:Row[]=[],documents:Row[]=[];if(lead.companyId)[activities,quotes,orders,samples,reports,payments,documents]=await Promise.all([related(db.orm.public.Activity,lead.companyId),related(db.orm.public.Quotation,lead.companyId),related(db.orm.public.WorkOrder,lead.companyId),related(db.orm.public.Sample,lead.companyId),related(db.orm.public.Report,lead.companyId),related(db.orm.public.Payment,lead.companyId),related(db.orm.public.Document,lead.companyId)]);
 const quoted=quotes.reduce((a,x)=>a+Number(x.totalAmount||0),0),confirmed=orders.reduce((a,x)=>a+Number(x.totalAmount||0),0),received=payments.reduce((a,x)=>a+Number(x.amount||0),0);const journey=[{label:"Enquiry",count:1,done:true,icon:<Phone size={17}/>},{label:"Activities",count:activities.length,done:activities.length>0,icon:<CalendarDays size={17}/>},{label:"Quotation",count:quotes.length,done:quotes.length>0,icon:<CircleDollarSign size={17}/>},{label:"Order",count:orders.length,done:orders.length>0,icon:<ClipboardList size={17}/>},{label:"Samples",count:samples.length,done:samples.length>0,icon:<FlaskConical size={17}/>},{label:"Reports",count:reports.length,done:reports.length>0,icon:<FileText size={17}/>},{label:"Payment",count:payments.length,done:payments.length>0,icon:<WalletCards size={17}/> }];
 return <div className="lead-profile-page lead-journey-page"><div className="lead-profile-back"><Link href={lead.source==="Inbound Call"?"/admin/leads/inbound":"/admin/leads"}><ArrowLeft size={16}/>Back to {lead.source==="Inbound Call"?"Inbound Calls":"Leads"}</Link></div><header className="lead-profile-header"><div><span>{lead.source==="Inbound Call"?"Inbound Call Journey":"Lead Profile"}</span><h1>{lead.name}</h1><div className="lead-profile-company-text"><Building2 size={15}/>{lead.company}</div></div><span className="lead-profile-status">{lead.status}</span></header>
 <section className="journey-strip">{journey.map((x,i)=><div className={`journey-step ${x.done?"done":""}`} key={x.label}><div className="journey-step-icon">{x.done?<CheckCircle2 size={17}/>:x.icon}</div><div><strong>{x.label}</strong><span>{x.count} record{x.count===1?"":"s"}</span></div>{i<journey.length-1&&<ArrowRight className="journey-arrow" size={15}/>}</div>)}</section>
 {!lead.companyId&&<section className="journey-warning"><Building2 size={20}/><div><strong>Link this lead to a CRM company to unlock the complete journey</strong><p>Quotations, activities, orders, samples, reports, payments and documents are connected through the company record. Select the correct company in Lead Control; do not create a duplicate client.</p></div></section>}
 {lead.companyId&&<section className="journey-summary"><Summary label="Quoted Value" value={money(quoted)}/><Summary label="Confirmed Business" value={money(confirmed)}/><Summary label="Payments Received" value={money(received)}/><Summary label="Documents" value={String(documents.length)}/></section>}
 <div className="lead-profile-grid"><section className="lead-profile-content"><article className="lead-profile-card"><div className="lead-profile-card-header"><div className="lead-profile-card-icon"><User size={18}/></div><div><h2>Contact Information</h2><p>Client and company details</p></div></div><div className="lead-profile-info-grid"><Info label="Contact Person" icon={<User size={15}/>}>{lead.name}</Info><Info label="Company" icon={<Building2 size={15}/>}>{lead.companyId?<Link href={`/admin/companies/${lead.companyId}`}>{lead.company}</Link>:lead.company}</Info><Info label="Phone" icon={<Phone size={15}/>}><a href={`tel:${lead.phone}`}>{lead.phone}</a></Info><Info label="Email" icon={<Mail size={15}/>}>{lead.email?<a href={`mailto:${lead.email}`}>{lead.email}</a>:"Not provided"}</Info></div></article><article className="lead-profile-card"><div className="lead-profile-card-header"><div className="lead-profile-card-icon"><ClipboardList size={18}/></div><div><h2>Testing Requirement</h2><p>Service requested by client</p></div></div><div className="lead-profile-service"><span>Requested Service</span><strong>{lead.service}</strong></div><div className="lead-profile-requirement"><span>Client Requirement</span><p>{lead.requirement}</p></div></article>
 {lead.companyId&&<article className="lead-profile-card journey-business-card"><div className="lead-profile-card-header"><div className="lead-profile-card-icon"><ReceiptText size={18}/></div><div><h2>Business Journey</h2><p>Everything recorded after the enquiry</p></div></div><JourneyRows activities={activities} quotes={quotes} orders={orders} samples={samples} reports={reports} payments={payments} documents={documents} companyId={lead.companyId}/></article>}
 <article className="lead-profile-card"><div className="lead-profile-card-header"><div className="lead-profile-card-icon"><CalendarDays size={18}/></div><div><h2>Lead Information</h2><p>Tracking, ownership and activity</p></div></div><div className="lead-profile-info-grid"><Info label="Sales Owner" icon={<UserRound size={15}/>}>{lead.salesOwner||"Unassigned"}</Info><Info label="Lead Source" icon={<MapPin size={15}/>}>{lead.source}</Info><Info label="Created" icon={<CalendarDays size={15}/>}>{fmt(lead.createdAt)}</Info><Info label="Next Follow-up" icon={<CalendarDays size={15}/>}>{follow(lead.nextFollowUp)}</Info><Info label="Last Updated" icon={<CalendarDays size={15}/>}>{fmt(lead.updatedAt)}</Info></div></article></section><aside className="lead-profile-editor"><LeadEditor lead={{id:lead.id,status:lead.status,notes:lead.notes??undefined,nextFollowUp:lead.nextFollowUp??undefined,companyId:lead.companyId,salesOwner:lead.salesOwner}}/></aside></div></div>}
function JourneyRows({activities,quotes,orders,samples,reports,payments,documents,companyId}:{activities:Row[];quotes:Row[];orders:Row[];samples:Row[];reports:Row[];payments:Row[];documents:Row[];companyId:string}){const rows=[{name:"Activities / Follow-ups",count:activities.length,detail:activities[0]?text(activities[0].title):"No activity recorded",href:`/admin/companies/${companyId}/activities/new`,action:"Add activity"},{name:"Quotations",count:quotes.length,detail:quotes[0]?`${text(quotes[0].quotationNumber)} · ${money(quotes[0].totalAmount)}`:"No quotation created",href:"/admin/quotations/new",action:"Create quotation"},{name:"Confirmed Orders",count:orders.length,detail:orders[0]?`${text(orders[0].workOrderNumber)} · ${money(orders[0].totalAmount)}`:"No order confirmed",href:`/admin/companies/${companyId}/work-orders/new`,action:"Add order"},{name:"Samples",count:samples.length,detail:samples[0]?`${text(samples[0].sampleNumber)} · ${text(samples[0].status)}`:"No sample recorded",href:"/admin/samples/new",action:"Add sample"},{name:"Reports",count:reports.length,detail:reports[0]?`${text(reports[0].reportNumber)} · ${text(reports[0].status)}`:"No report recorded",href:"/admin/reports/new",action:"Add report"},{name:"Payments",count:payments.length,detail:payments[0]?`${money(payments[0].amount)} · ${text(payments[0].status)}`:"No payment recorded",href:"/admin/payments/record",action:"Record payment"},{name:"Documents",count:documents.length,detail:documents[0]?text(documents[0].title):"No related document",href:"/admin/documents/new",action:"Add document"}];return <div className="journey-record-list">{rows.map(x=><div className="journey-record" key={x.name}><div><strong>{x.name}<b>{x.count}</b></strong><span>{x.detail}</span></div><Link href={x.href}>{x.action}<ArrowRight size={13}/></Link></div>)}</div>}
function Summary({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Info({label,icon,children}:{label:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="lead-profile-info-item"><span>{label}</span><div>{icon}<strong>{children}</strong></div></div>}
