import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowRight, CircleDollarSign, Clock3, FileText, ShieldAlert, Target, WalletCards } from "lucide-react";
import { db } from "@/src/prisma/db";
import "../management.css";
import "../v8-control.css";
import "../attention/attention.css";
import "./risk.css";

export const dynamic="force-dynamic";
type Row=Record<string,unknown>;
type Table="Lead"|"Quotation"|"WorkOrder"|"Payment";
async function rows(t:Table){try{return await(db.orm.public[t] as unknown as{all:()=>Promise<Row[]>}).all()}catch{return[]}}
const txt=(v:unknown)=>String(v||"").trim(),low=(v:unknown)=>txt(v).toLowerCase(),n=(v:unknown)=>Number(v||0);
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
const openLead=(s:unknown)=>!["inactive","cancelled","canceled","closed","rejected","void","won","lost"].includes(low(s));
const openQuote=(s:unknown)=>!["accepted","approved","won","closed","rejected","cancelled","canceled","expired"].includes(low(s));
const validOrder=(s:unknown)=>!["cancelled","canceled","rejected","void"].includes(low(s));
const paid=(s:unknown)=>["received","paid","collected","completed"].includes(low(s));
function ageDays(v:unknown){if(!v)return 0;const d=new Date(String(v));if(Number.isNaN(d.getTime()))return 0;return Math.max(0,Math.floor((Date.now()-d.getTime())/86400000))}
function bucket(d:number){if(d<=7)return"0–7d";if(d<=15)return"8–15d";if(d<=30)return"16–30d";return"31+d"}
export default async function Page(){
 const [leads,quotes,orders,payments]=await Promise.all([rows("Lead"),rows("Quotation"),rows("WorkOrder"),rows("Payment")]);
 const ol=leads.filter(x=>openLead(x.status)),oq=quotes.filter(x=>openQuote(x.status)),vo=orders.filter(x=>validOrder(x.status)),rp=payments.filter(x=>paid(x.status));
 const business=vo.reduce((a,x)=>a+n(x.totalAmount),0),collections=rp.reduce((a,x)=>a+n(x.amount),0),outstanding=Math.max(business-collections,0);
 const quoteValue=oq.reduce((a,x)=>a+n(x.totalAmount),0),oldQuotes=oq.filter(x=>ageDays(x.sentDate||x.quotationDate||x.createdAt)>30),oldLeads=ol.filter(x=>ageDays(x.createdAt)>30),unowned=[...ol,...oq].filter(x=>!txt(x.salesOwner));
 const buckets=["0–7d","8–15d","16–30d","31+d"].map(label=>({label,leads:ol.filter(x=>bucket(ageDays(x.createdAt))===label).length,quotes:oq.filter(x=>bucket(ageDays(x.sentDate||x.quotationDate||x.createdAt))===label).length,value:oq.filter(x=>bucket(ageDays(x.sentDate||x.quotationDate||x.createdAt))===label).reduce((a,x)=>a+n(x.totalAmount),0)}));
 const owner=new Map<string,{pipeline:number;business:number;collections:number;openQuotes:number}>();const get=(v:unknown)=>{const k=txt(v)||"Unassigned";if(!owner.has(k))owner.set(k,{pipeline:0,business:0,collections:0,openQuotes:0});return owner.get(k)!};
 oq.forEach(x=>{const a=get(x.salesOwner);a.pipeline+=n(x.totalAmount);a.openQuotes++});vo.forEach(x=>get(x.salesOwner).business+=n(x.totalAmount));rp.forEach(x=>{const wo=orders.find(w=>String(w.id)===String(x.workOrderId)),qt=quotes.find(q=>String(q.id)===String(x.quotationId));get(wo?.salesOwner||qt?.salesOwner).collections+=n(x.amount)});
 const ownerRows=[...owner.entries()].sort((a,b)=>Math.max(b[1].business-b[1].collections,0)-Math.max(a[1].business-a[1].collections,0));
 return <main className="mi-page"><header className="mi-hero mx-hero"><div><span>V8 • COMMERCIAL RISK INTELLIGENCE</span><h1>Pipeline, Aging & Collection Exposure</h1><p>See where commercial value is sitting, how old it is, who owns it and where management attention is required.</p></div><Link href="/admin/management"><ArrowLeft size={17}/> Management</Link></header>
 <section className="rx-kpis"><Link href="/admin/quotations"><FileText/><span>Open pipeline</span><strong>{money(quoteValue)}</strong><small>{oq.length} open quotations</small></Link><Link href="/admin/payments"><WalletCards/><span>Outstanding exposure</span><strong>{money(outstanding)}</strong><small>{business?Math.round(outstanding/business*100):0}% of business</small></Link><Link href="/admin/quotations"><Clock3/><span>Quotes older than 30d</span><strong>{oldQuotes.length}</strong><small>{money(oldQuotes.reduce((a,x)=>a+n(x.totalAmount),0))} exposed</small></Link><Link href="/admin/leads"><Target/><span>Leads older than 30d</span><strong>{oldLeads.length}</strong><small>still active</small></Link><Link href="/admin/management/attention"><ShieldAlert/><span>Ownership gaps</span><strong>{unowned.length}</strong><small>open commercial records</small></Link></section>
 <section className="mi-grid"><article className="mi-panel"><div className="mi-panel-head"><div><span>AGING DISTRIBUTION</span><h2>How long work has been sitting open</h2></div><Clock3/></div><div className="rx-aging">{buckets.map(b=><div key={b.label}><strong>{b.label}</strong><span>{b.leads} leads</span><span>{b.quotes} quotations</span><b>{money(b.value)}</b></div>)}</div></article><article className="mi-panel"><div className="mi-panel-head"><div><span>COLLECTION HEALTH</span><h2>Business realization</h2></div><CircleDollarSign/></div><div className="rx-money"><div><span>Business</span><strong>{money(business)}</strong></div><div><span>Collected</span><strong>{money(collections)}</strong></div><div className="risk"><span>Outstanding</span><strong>{money(outstanding)}</strong></div></div><div className="mi-bar"><i style={{width:`${Math.min(100,business?collections/business*100:0)}%`}}/></div><p>{business?Math.round(collections/business*100):0}% of recorded business has been collected.</p></article></section>
 <section className="mi-panel"><div className="mi-panel-head"><div><span>OWNER EXPOSURE</span><h2>Pipeline and outstanding responsibility by sales owner</h2></div><AlertTriangle/></div><div className="mi-table-wrap"><table className="mi-owner-table"><thead><tr><th>Owner</th><th>Open Quotes</th><th>Pipeline</th><th>Business</th><th>Collections</th><th>Outstanding</th><th>Collection %</th><th></th></tr></thead><tbody>{ownerRows.map(([name,a])=>{const out=Math.max(a.business-a.collections,0);return <tr key={name}><td><strong>{name}</strong></td><td>{a.openQuotes}</td><td>{money(a.pipeline)}</td><td>{money(a.business)}</td><td>{money(a.collections)}</td><td className={out>0?"mi-warning":""}>{money(out)}</td><td>{a.business?Math.round(a.collections/a.business*100):0}%</td><td><Link className="mi-view" href={`/admin/management/owner/${encodeURIComponent(name)}`}>View <ArrowRight size={13}/></Link></td></tr>})}</tbody></table></div></section>
 <section className="mi-panel rx-old"><div className="mi-panel-head"><div><span>AGED PIPELINE</span><h2>Open quotations older than 30 days</h2></div><FileText/></div><div className="mx-list">{oldQuotes.length?oldQuotes.sort((a,b)=>ageDays(b.sentDate||b.quotationDate||b.createdAt)-ageDays(a.sentDate||a.quotationDate||a.createdAt)).slice(0,60).map(x=><Link href={`/admin/quotations/${x.id}`} className="mx-row" key={String(x.id)}><div><strong>{txt(x.quotationNumber)||"Quotation"}</strong><span>{txt(x.service)||"Service"} · Owner: {txt(x.salesOwner)||"Unassigned"}</span></div><div><b>{money(n(x.totalAmount))}</b><small>{ageDays(x.sentDate||x.quotationDate||x.createdAt)} days open</small></div><ArrowRight/></Link>):<p className="mx-empty">No open quotations older than 30 days.</p>}</div></section></main>;
}
