import Link from "next/link";
import { AlertTriangle, ArrowRight, BarChart3, CalendarClock, CircleDollarSign, ClipboardCheck, FileText, FlaskConical, Target, UsersRound } from "lucide-react";
import { db } from "@/src/prisma/db";
import "./management.css";

export const dynamic="force-dynamic";
type Row=Record<string,unknown>;
async function rows(table:"Company"|"Lead"|"Quotation"|"WorkOrder"|"Payment"|"Sample"){try{return await(db.orm.public[table] as unknown as{all:()=>Promise<Row[]>}).all()}catch{return[]}}
const n=(v:unknown)=>Number(v||0);const txt=(v:unknown)=>String(v||"").trim();const low=(v:unknown)=>txt(v).toLowerCase();
const active=(s:unknown)=>!["inactive","cancelled","canceled","closed","rejected","void","won","lost"].includes(low(s));
const openQuote=(s:unknown)=>!["accepted","approved","won","closed","rejected","cancelled","canceled","expired"].includes(low(s));
const validOrder=(s:unknown)=>!["cancelled","canceled","rejected","void"].includes(low(s));const paid=(s:unknown)=>["received","paid","collected","completed"].includes(low(s));
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
function sourceGroup(v:unknown){const s=low(v);if(!s)return"Unspecified";if(s.includes("website")||s.includes("web"))return"Website";if(s.includes("linkedin")||s.includes("digital")||s.includes("social"))return"Digital / LinkedIn";if(s.includes("reference")||s.includes("referral"))return"Reference";if(s.includes("field")||s.includes("visit")||s.includes("walk"))return"Field Marketing";if(s.includes("existing")||s.includes("repeat")||s.includes("recurring"))return"Existing / Recurring";return txt(v)}
function followState(x:Row){if(!x.nextFollowUp||!["won","lost","closed","cancelled","canceled"].every(s=>low(x.status)!==s))return"none";const d=new Date(String(x.nextFollowUp));if(Number.isNaN(d.getTime()))return"none";const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),day=new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();return day<today?"overdue":day===today?"today":"upcoming"}
export default async function ManagementPage(){
 const[companies,leads,quotes,orders,payments,samples]=await Promise.all([rows("Company"),rows("Lead"),rows("Quotation"),rows("WorkOrder"),rows("Payment"),rows("Sample")]);
 const liveLeads=leads.filter(x=>active(x.status)),liveQuotes=quotes.filter(x=>openQuote(x.status)),liveOrders=orders.filter(x=>validOrder(x.status));const business=liveOrders.reduce((a,x)=>a+n(x.totalAmount),0),collected=payments.filter(x=>paid(x.status)).reduce((a,x)=>a+n(x.amount),0),pending=Math.max(business-collected,0),sampleCount=samples.reduce((a,x)=>a+n(x.sampleCount||1),0);
 const overdue=liveLeads.filter(x=>followState(x)==="overdue").length,dueToday=liveLeads.filter(x=>followState(x)==="today").length,unread=leads.filter(x=>x.isRead===false).length;
 const sourceMap=new Map<string,number>();for(const lead of leads){const k=sourceGroup(lead.source);sourceMap.set(k,(sourceMap.get(k)||0)+1)}const sources=[...sourceMap.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6),maxSource=Math.max(1,...sources.map(x=>x[1]));
 const cards=[["Clients",companies.length,"Company master","/admin/companies",<UsersRound key="c"/>],["Active Leads",liveLeads.length,"Current sales pipeline","/admin/leads",<Target key="l"/>],["Open Quotations",liveQuotes.length,"Awaiting decision / follow-up","/admin/quotations",<FileText key="q"/>],["Business Value",money(business),`${liveOrders.length} valid orders`,"/admin/orders",<BarChart3 key="b"/>],["Collected",money(collected),"Recorded received payments","/admin/payments",<CircleDollarSign key="p"/>],["Pending",money(pending),"Business value less collections","/admin/payments",<ClipboardCheck key="d"/>],["Samples",sampleCount,"Recorded sample volume","/admin/samples",<FlaskConical key="s"/>]] as const;
 return <main className="mi-page"><header className="mi-hero"><div><span>MANAGEMENT INTELLIGENCE • V5</span><h1>Hyderabad Business Command Center</h1><p>A single management view of sales pipeline, confirmed business, collections and operational workload.</p></div><Link href="/admin/business">Open Business MIS <ArrowRight size={17}/></Link></header>
 <section className="mi-kpis">{cards.map(([title,value,note,href,icon])=><Link href={href} className="mi-card" key={title}><div className="mi-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{note}</small></div><ArrowRight className="mi-arrow" size={16}/></Link>)}</section>
 <section className="mi-grid"><article className="mi-panel"><div className="mi-panel-head"><div><span>SALES CONTROL</span><h2>Pipeline at a glance</h2></div><Target/></div><div className="mi-flow"><div><strong>{liveLeads.length}</strong><span>Active Leads</span></div><i>→</i><div><strong>{liveQuotes.length}</strong><span>Open Quotes</span></div><i>→</i><div><strong>{liveOrders.length}</strong><span>Orders</span></div></div><Link href="/admin/follow-ups">Review follow-ups <ArrowRight size={15}/></Link></article>
 <article className="mi-panel mi-finance"><div className="mi-panel-head"><div><span>COLLECTION CONTROL</span><h2>Revenue position</h2></div><CircleDollarSign/></div><div className="mi-money"><div><span>Business</span><strong>{money(business)}</strong></div><div><span>Collected</span><strong>{money(collected)}</strong></div><div><span>Pending</span><strong>{money(pending)}</strong></div></div><div className="mi-bar"><i style={{width:`${business?Math.min(100,(collected/business)*100):0}%`}}/></div><small>{business?Math.round((collected/business)*100):0}% of recorded business value collected</small></article></section>
 <section className="mi-grid"><article className="mi-panel"><div className="mi-panel-head"><div><span>LEAD SOURCE INTELLIGENCE</span><h2>Where opportunities originate</h2></div><BarChart3/></div><div className="mi-sources">{sources.length?sources.map(([name,count])=><div className="mi-source" key={name}><div><span>{name}</span><strong>{count}</strong></div><div className="mi-source-bar"><i style={{width:`${(count/maxSource)*100}%`}}/></div></div>):<p className="mi-muted">Lead source data will appear as CRM leads are recorded.</p>}</div></article>
 <article className="mi-panel"><div className="mi-panel-head"><div><span>MANAGEMENT ATTENTION</span><h2>Items needing action</h2></div><AlertTriangle/></div><div className="mi-alerts"><Link href="/admin/follow-ups"><CalendarClock/><div><strong>{overdue}</strong><span>Overdue follow-ups</span></div><ArrowRight/></Link><Link href="/admin/follow-ups"><CalendarClock/><div><strong>{dueToday}</strong><span>Follow-ups due today</span></div><ArrowRight/></Link><Link href="/admin/leads"><Target/><div><strong>{unread}</strong><span>Unread / new leads</span></div><ArrowRight/></Link><Link href="/admin/quotations"><FileText/><div><strong>{liveQuotes.length}</strong><span>Open quotations</span></div><ArrowRight/></Link></div></article></section>
 <section className="mi-next"><div><span>V5 NEXT LAYER</span><h2>Management automation foundation is now active</h2></div><div className="mi-next-items"><span>Lead source intelligence ✓</span><span>Management alerts ✓</span><span>Individual sales contribution</span><span>Monthly report automation</span></div></section></main>
}
